[section]
name = "Town"
street = "Street 12"
town = "12345 Town"
telephone = "123456789"
telefax = "987654321"
contact_mail = "contact@jdav-town.de"
board_mail = "board@jdav-town.de"
crisis_intervention_mail = "crisis@jdav-town.de"
iban = "DE42 4242 4242 4242 4242 42"
account_holder = "DAV Town"
responsible_mail = "responsible@jdav-town.de"
digital_mail = "digital@jdav-town.de"
admins = [['Admin', 'admin@jdav-town.de']]

[LJP]
v32_head_organisation = """
LJP application recipient header
"""

[misc]
allowed_email_domains_for_invite_as_user = ['alpenverein-town.de']
send_from_association_email = true
domain = 'jdav-town.de'

[finance]
allowance_per_day = 22
max_night_cost = 11

[links]
cloud = "https://nextcloud.com"
dav_360 = "https://dav360.de"
wiki = "https://wikipedia.org"
docs = "https://jdav-hd.de/static/docs"
registration_form = "download-me"

[startpage]
redirect_url = ''
root_section = 'wir'
recent_section = 'aktuelles'
reports_section = 'berichte'

[django]
deployed = true
debug = false
secret_key = 'secret key'
allowed_hosts = ['jdav-town.de']
host = 'jdav-town.de'
media_root = '/var/www/jdav_web/media'
static_root = '/var/www/jdav_web/static'
broker_url = 'redis://redis:6379/0'
memcached_url = 'cache:11211'

[mail]
host = 'host'
user = 'kompass-mailagent'
password = 'password'
default_sending_address = 'info@jdav-town.de'
default_sending_name = 'JDAV Town'

[database]
host = 'host'
port = 3306
database = 'kompass'
user = 'kompass'
password = 'kompass-db-user-password'

# OpenID Connect (OIDC) authentication settings
[oidc]
# Enable OIDC authentication
enabled = false
# Relying Party (RP) client ID from your OIDC provider
rp_client_id = ''
# Relying Party (RP) client secret from your OIDC provider
rp_client_secret = ''
# OIDC Provider (OP) authorization endpoint URL
op_authorization_endpoint = ''
# OIDC Provider (OP) token endpoint URL
op_token_endpoint = ''
# OIDC Provider (OP) user info endpoint URL
op_user_endpoint = ''
# OIDC Provider (OP) JSON Web Key Set (JWKS) endpoint URL
op_jwks_endpoint = ''
# Signature algorithm for verifying ID tokens (typically RS256)
rp_sign_algo = 'RS256'
# Space-separated list of OAuth scopes to request
rp_scopes = 'openid email profile'
# Claim name in the ID token containing the username
claim_username = 'username'
# Claim name in the ID token containing the user's first name
claim_first_name = 'given_name'
# Claim name in the ID token containing the user's last name
claim_last_name = 'last_name'
# Group name in the ID token that grants staff permissions
group_staff = 'staff'
# Group name in the ID token that grants superuser permissions
group_superuser = 'superuser'
